language: erlang

env:
   - ST=Squeak-4.3
   - ST=Squeak-4.4
   - ST=Squeak-4.5
   - ST=Squeak-Trunk
matrix:
   allow_failures:
   - env: ST=Squeak-Trunk

# blacklist
branches:
  except:
    - master

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script: $BUILDER_CI_HOME/testTravisCI.sh
